### ISSUE TITLE
Specifiy scale required for all methods clearly

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/BRCindicators#13] opened 2018-05-22 09:22 UTC
This should be in the help docs and in the vignette

**Comment by drnickisaac** [comment] 2019-07-09 11:35
At present the `rescale_species()` and `bootstrap_indicator()` work with data on the measurement scale, but `bma()` required log or logit scale.

**Comment by DylanCarbone** [comment] 2024-09-30 12:32
duplicate of #12

**Closed by DylanCarbone** 2024-09-30 12:32 UTC
